### PR TITLE
Implementing capstone project PR

### PR DESCRIPTION
**Pull request by selma-belhadj**
In this PR, I have done the following tasks:

- Personalizing the content of my page with a topic that is different from the one in the original design.
- Using CSS to style the website.
- Using JavaScript to show and hide the mobile menu.
- Rendering the speakers dynamically.
- Using JavaScript to show more and show fewer speakers.

### CODE REVIEW

**Comment by selma-belhadj** [comment]
I have recorded the video as required to present the project features. Kindly check this [presentation video](https://www.loom.com/share/b201054db4b9429c815de310aea7e8fb)

**Comment by sheylaPozo** [comment]
## Status: ✔️ Project Approved ✔️ 
----

Hello @selma-belhadj  🔥 

> # Excellent work on your project, it looks very professional and it's completed. Congrats on the good work!

surprised

Now you can celebrate! 🥇 🚀 👍 💯 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️
`There's nothing left to say but time to merge! 😊`

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by selma-belhadj** [comment]
@sheylaPozo Thank you so much for your fast review and your support 😁

**Comment by sheylaPozo** [comment]
:) no problem

**Pull request merged**
